# Generated by Django 5.2.1 on 2025-06-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_member_address2_member_address3'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address2',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
    ]
