# Generated by Django 5.2.1 on 2025-05-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='major',
            field=models.CharField(default='컴퓨터공학', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default='홍길동', max_length=100),
            preserve_default=False,
        ),
    ]
