# Generated by Django 5.2.1 on 2025-06-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bcontent',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
