# Generated by Django 5.2.1 on 2025-06-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='')),
                ('sub_image1', models.ImageField(upload_to='')),
                ('sub_image2', models.ImageField(upload_to='')),
                ('create_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
        ),
    ]
