# Generated by Django 5.2.1 on 2025-05-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuscore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuscore',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
