# Generated by Django 5.2.1 on 2025-05-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuscore', '0002_stuscore_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stuscore',
        ),
    ]
