# Generated by Django 5.2.1 on 2025-05-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stuscore', '0003_delete_stuscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('kor', models.IntegerField(default=0)),
                ('eng', models.IntegerField(default=0)),
                ('math', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('avg', models.IntegerField(default=0)),
            ],
        ),
    ]
