# Generated by Django 5.2.1 on 2025-05-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuscore', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuscore',
            name='id',
        ),
        migrations.AlterField(
            model_name='stuscore',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
